import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const YEARS = Array.from({ length: 17 }, (_, i) => 2026 - i);

export const adminStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#F3F7F5' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#DCE6E2',
  },
  adminOpenBtn: {
    marginRight: 12,
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  adminOpenBtnText: {
    fontSize: 18,
    color: '#14283D',
  },
  headerSide: { minWidth: 64 },
  headerEyebrow: {
    color: COLORS.gold,
    fontWeight: '700',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  headerTitle: {
    color: '#14283D',
    fontWeight: '900',
    fontSize: 24,
    marginTop: 2,
  },
  headerAction: { color: '#0F8A72', fontWeight: '800', fontSize: 13 },
  logoutPill: {
    backgroundColor: '#FDF0F0',
    borderWidth: 1,
    borderColor: '#F5C6CB',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  logoutPillText: { color: '#C0392B', fontWeight: '800', fontSize: 13 },
  logoutModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(20,40,61,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  logoutModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
  },
  logoutModalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#14283D',
    marginBottom: 14,
    textAlign: 'center',
  },
  logoutModalActions: { flexDirection: 'row', gap: 10 },
  logoutModalBtn: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: '#F3F7F5',
  },
  logoutModalBtnText: { color: '#14283D', fontWeight: '800' },
  logoutModalConfirm: { backgroundColor: '#C0392B' },
  content: { padding: 16, paddingBottom: 40 },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#D2DDD7',
  },
  cardTitle: { color: '#14283D', fontSize: 15, fontWeight: '800', marginBottom: 10 },
  muted: { color: '#5A6B68', fontSize: 13, lineHeight: 19 },
  error: { color: '#c0392b', fontSize: 13, marginBottom: 10 },
  success: { color: '#1e8449', fontSize: 13, fontWeight: '700', marginBottom: 10 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  statTile: {
    width: '47.6%',
    minHeight: 86,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#D2DDD7',
    borderRadius: 16,
    padding: 14,
  },
  statValue: { color: '#14283D', fontSize: 22, fontWeight: '900' },
  statLabel: { color: '#5A6B68', fontSize: 12, fontWeight: '700', marginTop: 4 },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D2DDD7',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 12,
  },
  searchInput: { flex: 1, fontSize: 16, color: '#14283D' },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D2DDD7',
    padding: 14,
    marginBottom: 10,
    minHeight: 72,
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.adminHero,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: '#ffffff', fontWeight: '900', fontSize: 15 },
  listTitle: { color: '#14283D', fontWeight: '800', fontSize: 15 },
  listMeta: { color: '#5A6B68', fontSize: 12, marginTop: 3 },
  chevron: { color: '#0F8A72', fontWeight: '800' },
  rank: { width: 28, color: COLORS.primary, fontWeight: '900', fontSize: 15 },
  rankTop: { color: COLORS.gold },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    backgroundColor: '#F3F7F5',
    borderWidth: 1,
    borderColor: '#D2DDD7',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipOn: { backgroundColor: COLORS.accent, borderColor: COLORS.accent },
  // Pill that pairs a SubjectBadge tile with the subject name
  subjectChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 6,
    paddingVertical: 6,
  },
  chipText: { color: '#14283D', fontWeight: '700', fontSize: 12 },
  chipTextOn: { color: '#ffffff' },
  fieldLabel: { color: '#14283D', fontWeight: '700', fontSize: 13, marginBottom: 6, marginTop: 10 },
  input: {
    backgroundColor: '#F3F7F5',
    borderWidth: 1,
    borderColor: '#D2DDD7',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    color: '#14283D',
  },
  textarea: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  primaryBtn: {
    backgroundColor: COLORS.accent,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 14,
  },
  primaryBtnText: { color: '#ffffff', fontWeight: '800', fontSize: 15 },
  dangerBtn: {
    backgroundColor: '#fdf0f0',
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#f5c6cb',
  },
  dangerBtnText: { color: '#c0392b', fontWeight: '800', fontSize: 12 },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#D2DDD7',
    marginBottom: 14,
    overflow: 'hidden',
  },
  tab: { flex: 1, paddingVertical: 12, alignItems: 'center' },
  tabOn: { backgroundColor: COLORS.accent },
  tabText: { color: '#5A6B68', fontWeight: '800', fontSize: 13 },
  tabTextOn: { color: '#ffffff' },
  empty: { color: '#5A6B68', textAlign: 'center', marginTop: 24, fontSize: 14 },
});
