import { StyleSheet } from 'react-native';
import { COLORS } from '../../constants/colors';

export const YEARS = Array.from({ length: 17 }, (_, i) => 2026 - i);

/**
 * Admin chrome is intentionally different from the student study UI:
 * dark ops header, charcoal/gold hero, navy actions — not warm paper + study photos.
 */
export const adminStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#E8EEF0' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 12,
    backgroundColor: COLORS.adminHero,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(196, 163, 90, 0.35)',
  },
  adminOpenBtn: {
    marginRight: 12,
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: 'rgba(196, 163, 90, 0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  adminOpenBtnText: {
    fontSize: 18,
    color: COLORS.gold,
  },
  headerSide: { minWidth: 64 },
  headerEyebrow: {
    color: COLORS.gold,
    fontWeight: '700',
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  headerTitle: {
    color: COLORS.textWhite,
    fontWeight: '900',
    fontSize: 24,
    marginTop: 2,
  },
  headerAction: { color: COLORS.gold, fontWeight: '800', fontSize: 13 },
  logoutPill: {
    backgroundColor: 'rgba(253, 240, 240, 0.12)',
    borderWidth: 1,
    borderColor: 'rgba(245, 198, 203, 0.55)',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  logoutPillText: { color: '#F5C6CB', fontWeight: '800', fontSize: 13 },
  logoutModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(20,40,61,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  logoutModalCard: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: COLORS.surfaceWhite,
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
  },
  logoutModalTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.primary,
    marginBottom: 14,
    textAlign: 'center',
  },
  logoutModalActions: { flexDirection: 'row', gap: 10 },
  logoutModalBtn: {
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: COLORS.background,
  },
  logoutModalBtnText: { color: COLORS.primary, fontWeight: '800' },
  logoutModalConfirm: { backgroundColor: COLORS.wrong },
  content: { padding: 16, paddingBottom: 40 },
  card: {
    backgroundColor: COLORS.surfaceWhite,
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cardTitle: { color: COLORS.primary, fontSize: 15, fontWeight: '800', marginBottom: 10 },
  muted: { color: COLORS.textMuted, fontSize: 13, lineHeight: 19 },
  error: { color: COLORS.wrong, fontSize: 13, marginBottom: 10 },
  success: { color: COLORS.correct, fontSize: 13, fontWeight: '700', marginBottom: 10 },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 14,
  },
  statTile: {
    width: '47.6%',
    minHeight: 86,
    backgroundColor: COLORS.surfaceWhite,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    padding: 14,
  },
  // First KPI should dominate — filled navy tile.
  statTileFeatured: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  statValue: { color: COLORS.primary, fontSize: 22, fontWeight: '900' },
  statValueOnDark: { color: COLORS.textWhite },
  statLabel: { color: COLORS.textMuted, fontSize: 12, fontWeight: '700', marginTop: 4 },
  statLabelOnDark: { color: COLORS.textOnDark },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surfaceWhite,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 12,
  },
  searchInput: { flex: 1, fontSize: 16, color: COLORS.primary },
  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.surfaceWhite,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 14,
    marginBottom: 10,
    minHeight: 72,
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: COLORS.adminHero,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: COLORS.textWhite, fontWeight: '900', fontSize: 15 },
  listTitle: { color: COLORS.primary, fontWeight: '800', fontSize: 15 },
  listMeta: { color: COLORS.textMuted, fontSize: 12, marginTop: 3 },
  chevron: { color: COLORS.gold, fontWeight: '800' },
  rank: { width: 28, color: COLORS.primary, fontWeight: '900', fontSize: 15 },
  rankTop: { color: COLORS.gold },
  chipWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipOn: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  subjectChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingLeft: 6,
    paddingVertical: 6,
  },
  chipText: { color: COLORS.primary, fontWeight: '700', fontSize: 12 },
  chipTextOn: { color: COLORS.textWhite },
  fieldLabel: { color: COLORS.primary, fontWeight: '700', fontSize: 13, marginBottom: 6, marginTop: 10 },
  input: {
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    fontSize: 15,
    color: COLORS.primary,
  },
  textarea: {
    minHeight: 88,
    textAlignVertical: 'top',
  },
  primaryBtn: {
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 14,
  },
  primaryBtnText: { color: COLORS.textWhite, fontWeight: '800', fontSize: 15 },
  secondaryBtn: {
    backgroundColor: COLORS.surfaceWhite,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: COLORS.gold,
  },
  secondaryBtnText: { color: COLORS.primary, fontWeight: '800', fontSize: 15 },
  dangerBtn: {
    backgroundColor: COLORS.wrongBg,
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#F5C6CB',
  },
  dangerBtnText: { color: COLORS.wrong, fontWeight: '800', fontSize: 12 },
  tabRow: {
    flexDirection: 'row',
    backgroundColor: COLORS.surfaceWhite,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 14,
    overflow: 'hidden',
  },
  tab: { flex: 1, paddingVertical: 12, alignItems: 'center' },
  tabOn: { backgroundColor: COLORS.primary },
  tabText: { color: COLORS.textMuted, fontWeight: '800', fontSize: 13 },
  tabTextOn: { color: COLORS.textWhite },
  empty: { color: COLORS.textMuted, textAlign: 'center', marginTop: 24, fontSize: 14 },

  // Ops-style hero — intentionally not the student study photo.
  consoleHero: {
    height: 168,
    borderRadius: 16,
    overflow: 'hidden',
    marginBottom: 14,
    backgroundColor: COLORS.adminHero,
    justifyContent: 'flex-end',
  },
  consoleHeroImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
  },
  consoleHeroScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(12, 18, 28, 0.62)',
  },
  consoleHeroContent: {
    padding: 16,
  },
  consoleHeroKicker: {
    color: COLORS.gold,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    marginBottom: 6,
  },
  consoleHeroTitle: {
    color: COLORS.textWhite,
    fontSize: 20,
    fontWeight: '900',
    marginBottom: 6,
  },
  consoleHeroBody: {
    color: COLORS.textOnDark,
    fontSize: 13,
    lineHeight: 18,
    maxWidth: 320,
  },
});
